### ISSUE TITLE
Infinity Symbols are not read correctly in TimingPoints

### ISSUE THREAD

**Issue by HoLLy-HaCKeR** [Francesco149/oppai-ng#11]
When a Timing Point contains an infinity symbol (∞), the parser throws a syntax error and does not continue. Since osu! uses `float.Parse(string)` on the line split by `','`, it can handle this. NaN may also not be accepted by oppai (and is accepted by osu!), but I have not yet tested this.

Beatmap containing this behaviour (ext. changed to .txt):
[A Himitsu - Cosmic Storm (JustM3) [idk dude].txt](https://github.com/Francesco149/oppai-ng/files/1267723/A.Himitsu.-.Cosmic.Storm.JustM3.idk.dude.txt)

---

Another thing I noticed is that with extreme sliders, oppai does create correct star ratings. I didn't think this was worth its own issue but I wanted to report it anyway. The beatmap below uses 2 rather extreme sliders placed at the same time to achieve a star rating of about 35000, but oppai reports 0.91 stars and 0.74pp.
[A Himitsu - Cosmic Storm (JustM3) [pp is overrated].txt](https://github.com/Francesco149/oppai-ng/files/1267736/A.Himitsu.-.Cosmic.Storm.JustM3.pp.is.overrated.txt)

**Comment by Francesco149** [comment]
hey, thanks for the accurate analysis, didn't know it was possible to get edge cases such as infinity in timing points, will fix when I can

as for extreme sliders, id say that's simply because I don't account for sliders or slider points at all because the calculations are expensive
