### ISSUE TITLE
Python binding ?

### ISSUE THREAD

**Issue by Renondedju** [Francesco149/oppai-ng#14]
Is there any way to have a small tutorial on how to compile oppai-ng for python ?

**Comment by Francesco149** [comment]
there are no bindings yet, but i wrote a pure python implementation: https://github.com/Francesco149/pyttanko

**Comment by Renondedju** [comment]
Nice !
Ty so much man <3

**Comment by Renondedju** [comment]
Do you plan on doing a binding ?
Because the pure python implementation isn't this fast (compared to oppai ng) and don't have the taiko expreimental pp calc

**Comment by Francesco149** [comment]
some day, but not anytime soon
