### ISSUE TITLE
Cache Use?

### ISSUE THREAD

**Issue by TheMeq** [Francesco149/oppai-ng#15]
Hi, if my code is using the following: 

`(New-Object System.Net.WebClient).DownloadString("https://osu.ppy.sh/osu/37658") | ./oppai -`

If I want to get the details for a combination of mods, whats the best way to reuse the osu file downloaded above instead of redownloading it again each time.

**Comment by Francesco149** [comment]
i don't use windows so I don't know if you can pipe downloadstring into a file, but try:

```
(New-Object System.Net.WebClient).DownloadString("https://osu.ppy.sh/osu/37658") > something.osu
oppai something.osu
```

**Comment by Francesco149** [comment]
closing this, reopen if you have further issues with this
