### ISSUE TITLE
inaccurate calc: 1206929 on taiko

### ISSUE THREAD

**Issue by thehowl** [Francesco149/oppai-ng#16]
https://osu.ppy.sh/b/1206929 (not a converted)

`curl https://osu.ppy.sh/osu/1206929 | ./oppai - -taiko` gives the following:

```
AR9 OD6 HP7
300 hitwindow: 31.5 ms
1170 circles, 762 sliders, 1 spinners
2692 max combo
16.48 stars
100%
1326.11 speed pp
140.82 acc pp

1570.84 pp
```

Stars on osu! website are 10.13, and since on oppai they are 16.48, pp receives a massive boost.

![image](https://user-images.githubusercontent.com/4681308/31019375-cace0530-a52f-11e7-8b3f-9570d4a3bb4b.png)

**Comment by Francesco149** [comment]
lazer shows incorrect stars as well (6.85), so there's probably something wrong in both implementations. guess I'll have to look deeper into this...

![](http://hnng.moe/f/UpG)

**Comment by Francesco149** [comment]
for whatever reason, lazer skips a ton of objects (the .osu files has 1933 hitobjects but lazer only reports 1469) :thinking:

**Comment by Francesco149** [comment]
oh also I noticed that there's a step i skipped in the beatmap conversion where hitobjects with the same start time get merged into strong hits, that might help fixing converted maps later

**Comment by Francesco149** [comment]
if I skip the beatmap conversion logic it gives the correct star rating, so maybe we're not supposed to run the conversion on maps that have mode=taiko

**Comment by Francesco149** [comment]
this patch fixes this map but I don't know if it breaks other maps:

```
diff --git a/oppai.c b/oppai.c
index 3358c8f..b08cdb1 100644
--- a/oppai.c
+++ b/oppai.c
@@ -2372,6 +2372,10 @@ int32_t d_taiko(struct diff_calc* d, uint32_t mods)
         cur->rim = (*o->sound_types &
             (SOUND_CLAP|SOUND_WHISTLE)) != 0;
 
+        if (b->mode == MODE_TAIKO) {
+            goto continue_loop;
+        }
+
         if (o->type & OBJ_SLIDER)
         {
             /* TODO: too much indentation, pull this out */
```

pls test

**Comment by Francesco149** [comment]
last 2 commits should fix this issue and make diff calc for converted beatmaps a bit less useless (although still quite off)

**Comment by Francesco149** [comment]
this should be fixed, so I'm closing. reopen if needed
