### ISSUE TITLE
can't vaild a .osu file

### ISSUE THREAD

**Issue by lslqtz** [Francesco149/oppai-ng#19]
curl https://osu.ppy.sh/osu/850252 | oppai.exe - -m0 +DT 4x100 0x50 0xmiss 490x

but it work:
curl https://osu.ppy.sh/osu/1046847 | oppai.exe - -m0 +DT 4x100 0x50 0xmiss 490x

This .osu file has a space before "osu file format v14".
![1](https://user-images.githubusercontent.com/18650291/31851795-bf00a65a-b69f-11e7-8c10-a328dd4f2834.png)
![2](https://user-images.githubusercontent.com/18650291/31851799-c370b482-b69f-11e7-85bc-392487a81581.png)

**Comment by Francesco149** [comment]
yep, I already fixed this issue in the latest commit (found by the ripple guys), but i haven't released a new binary for it yet. you can compile from source if you want it right now
