### ISSUE TITLE
not a valid .osu file edge-cases

### ISSUE THREAD

**Issue by CloudMax94** [Francesco149/oppai-ng#26]
I have an application that process all approved beatmaps, and I found three that fail on the magic string check.
The beatmaps being: [135661](https://osu.ppy.sh/osu/135661), [157249](https://osu.ppy.sh/osu/157249), [797130](https://osu.ppy.sh/osu/797130)
135661 and 797130 both have linebreaks before the magic string.
157249 is missing the first character of the magic string. (the "o")

I assume this is more of an issue with the beatmap files, and the best solution is probably for the beatmap files to be updated, but I figured I might as well put up an issue, just in case.
I'm currently working around the first problem by simply trimming whitespace from the beginning of the file before passing it on to oppai (ojsama).
The second problem is a bit more annoying. I could do something along the lines of removing all characters up until the v and then appending the magic string, but it's a hacky solution.

There may be a place to report beatmap issues like this, I haven't looked into it.

**Comment by omkelderman** [comment]
skipping empty lines/whitespace at the beginning should probably a thing that oppai should do imo

the thing where it misses the o, now I wonder how the heck the official client parses that thing? :thinking::thinking::thinking::thinking::thinking::thinking::thinking::thinking:

**Comment by jamesguessis** [comment]
Perhaps the client only looks for the v on the first non empty line?

**Comment by omkelderman** [comment]
can confirm that a .osu file that starts with the following content has been successfully read by current cutting edge build:

```





some random bullshit kjsdhfkjsdhfk jhsdkjfh skdjhf ksdjhf kjsdhf kjt v14

[General]
```

**Comment by omkelderman** [comment]
or even without anything before `[General]` or other random bullshit without the `v14` im confused af now, it just does whatever, lets try actually removing the whole thing and adding it as a new osz, maybe that parser is different

*few moments later*
welp nope, it doesnt matter whatever the fuck I write before the `[General]`, it all works......

*after trying a few more random things*
ok if I do nothing (so completely delete the line) audio seems to not work :thinking: anything else, doesnt matter what (with or without v), works just fine.... including multiple lines with bullshit

**Comment by Francesco149** [comment]
yes I've noticed that the magic string is very inconsistent (sometimes having random whitespace in front of it) and I've already been stripping it but i guess it's not enough.

I'll consider dropping the magic string check all together

another problemn i think is still there is whitespace lines in hitobjects.

thanks for the reminders
