### ISSUE TITLE
Unknown output encording

### ISSUE THREAD

**Issue by MikiraSora** [Francesco149/oppai-ng#30]
i use oppai-ng.exe(oppai 1.1.40-b88).
![](https://puu.sh/z4Y10/4857491ad4.png)
![](https://puu.sh/z4YcL/7cac1ffb5d.png)

https://puu.sh/z4YgB/f6f3fe58e0.osu //test.osu

I don't know what's kind of encording should I use. lol

**Comment by MikiraSora** [comment]
Firetruck Console with GBK , LOL

**Comment by Francesco149** [comment]
lol i'm guessing localized powershell doesn't handle unicode well, but it's supposed to be utf-8
