### ISSUE TITLE
diff calc on https://osu.ppy.sh/b/15800 off (?)

### ISSUE THREAD

**Issue by LazyLea** [Francesco149/oppai-ng#32]
beatmap: [DragonForce - Through the Fire and Flames [Expert]](https://osu.ppy.sh/b/15800&m=0)

`3.63` stars according to oppai, `4.67` stars according to the website/api, `5.22` stars ingame, `3.64` stars in osu!lazer

who to believe 🤔 

- WubWoofWolf +HDHRDT 99.17% 1511/1512x | `378.73pp` oppai, `430.88.pp` api
- MillhioreF +HR 99.24% | `131.91pp` oppai, `206.21pp` api
- ShaggoN SS | `71.29pp` oppai, `123.14pp` api

**Comment by Francesco149** [comment]
matches site after the last pp updates
