### ISSUE TITLE
Unable to calculate Taiko PP

### ISSUE THREAD

**Issue by lslqtz** [Francesco149/oppai-ng#37]
Ver:oppai 1.1.52-b101
`curl https://osu.ppy.sh/osu/127233 --insecure|oppai - 8x100 0x50 0xmiss 291x -m1`
but...
![](https://user-images.githubusercontent.com/18650291/42376447-c2df768e-8151-11e8-859a-3d4799650c1c.png)

**Comment by kj415j45** [comment]
duplicated with #31
