### ISSUE TITLE
Segault in Taiko mode on non-Taiko maps

### ISSUE THREAD

**Issue by christopher-dG** [Francesco149/oppai-ng#38]
This happens with both standard maps I tested, it did not happen with a taiko one (this is on master branch).
```
[ ~ ] curl -s -o fd.osu https://osu.ppy.sh/osu/129891
[ ~ ] oppai fd.osu -m1                                
zsh: segmentation fault (core dumped)  oppai fd.osu -m1
 x [ ~ ] oppai fd.osu -taiko
zsh: segmentation fault (core dumped)  oppai fd.osu -taiko
 x [ ~ ] oppai -v
1.1.52
```

**Comment by christopher-dG** [comment]
Oops, this is likely a duplicate of #31.
FWIW, the beatmaps I tested were [Time Freeze](https://osu.ppy.sh/beatmapsets/158023#osu/555797) and [FD4D](https://osu.ppy.sh/beatmapsets/39804/#osu/129891).

**Comment by Francesco149** [comment]
ye taiko code is very broken atm, especially for non-taiko maps
