### ISSUE TITLE
https://osu.ppy.sh/b/871542 - crashes oppai

### ISSUE THREAD

**Issue by grumd** [Francesco149/oppai-ng#41]
It says it has no timing points, but it actually has those

![](https://vgy.me/qxx0In.png)

![](https://vgy.me/ZLRzli.png)

**Comment by omkelderman** [comment]
that is not a problem with oppai, that is this problem: https://github.com/ppy/osu-api/issues/131

**Comment by Francesco149** [comment]
yea it looks like the .osu file is one of those that get truncated to 1MB and since the event section is massive, both hitobjects and timing points are cut out. you'll have to download and extract the osz for this particular map until the issue is fixed on peppy's end

**Comment by Syriiin** [comment]
this appears to have been fixed recently. probably safe to close this issue now

**Comment by grumd** [comment]
Didn't check if it's fixed, but the issue can be closed.
