### ISSUE TITLE
Compiler Errors with C++17/MSVC

### ISSUE THREAD

**Issue by MaxKruse** [Francesco149/oppai-ng#48]
Hi, maybe im just retarded but i cant seem to compile oppai when adding it to my project.

https://i.imgur.com/8UNA5qL.png

not sure if im at fault or msvc

**Comment by Francesco149** [comment]
oppai-ng is c, and it's not compatible with c++, so for c++ project you must include oppai.c without OPPAI_IMPLEMENTATION and then compile oppai.c separately as C

```
extern "C" {
#include "oppai.c"
}
```

and then add oppai.c to the project so it gets compiled

**Comment by MaxKruse** [comment]
Yea i was just stupid. Built oppai as static lib, linked and #define'd static header on includd, working now :)
