### ISSUE TITLE
Overflow in call to m_alloc

### ISSUE THREAD

**Issue by tadeokondrak** [Francesco149/oppai-ng#54]
[here](https://github.com/Francesco149/oppai-ng/blob/master/oppai.c#L1054)

With this file, m_alloc will be passed a number larger than sizeof(int) and crash:
```
[General]
Mode: 1
[HitObjects]
0,0,0,2,0,0,999999999,0,0,0,0,0,0
```

Would submit a PR to fix but I'm not sure of the underlying reasons why some functions take the types they do so I'd probably get it wrong

**Comment by tadeokondrak** [comment]
Also, with
```
[General]
Mode: 1
[HitObjects]
0,0,0,2,0,0,-5,0,0
0,0,0,2,0,0,0,0,0
```
malloc will be passed a negative number and cause memory corruption.

So, a fix would be something like
```c
if (nodes < 1) {
	return ERR_SYNTAX;
} else if (/* calculate if sizeof(int)*nodes fits into an int */) {
	return ERR_OOM;
}
```

**Comment by Francesco149** [comment]
nice find, this could be used to DDOS services relying on oppai, lol

will fix asap
