### ISSUE TITLE
Building issues on ARM platforms

### ISSUE THREAD

**Issue by szescxz** [Francesco149/oppai-ng#55]
Following the Linux installation guide in README, the binary file was compiled successfully, however it doesn't work with any beatmaps (even a test beatmap with only one hit object), throwing an error that reads "data was truncated, possibly because it was too big".
Tested on armv7l & aarch64. Other architectures (x86_64 & mips in my case) works fine. Cross-compiling with `gcc-arm-linux-gnueabihf` doesn't work either.
The Python module (installed with `pip install oppai`, not the pure Python one) also returns `-3`.

**Comment by Francesco149** [comment]
interesting. time to debug it on my raspberry pi

**Comment by Francesco149** [comment]
oooh it seems that on arm the EOF character is outside the range of ```char``` so the reading loop never detects it. I'll have to make it an ```int```

TIL
