### ISSUE TITLE
Obligatory Issue for Update

### ISSUE THREAD

**Issue by MaxKruse** [Francesco149/oppai-ng#67]
This is a documantory issue to keep track of the new pp update: https://osu.ppy.sh/home/news/2021-01-14-performance-points-updates

*henlo francesco men pliz when update is done?*

**Comment by wojtulinka** [comment]
pls update pp calc

**Comment by Duckbio** [comment]
pls update pp calc nu hurry tho take your time francesco <3

**Comment by Francesco149** [comment]
updated
