### ISSUE TITLE
OD, AR, HP and CS overrides seem to have no effect using python bindings

### ISSUE THREAD

**Issue by Jeglet** [Francesco149/oppai-ng#69]
```python
import sys
from oppai import *

ez = ezpp_new()
ezpp(ez, sys.argv[1])
ezpp_set_base_cs(ez, 3)
ezpp_set_base_ar(ez, 3)
ezpp_set_base_od(ez, 3)
ezpp_set_base_hp(ez, 3)
print("%g cs" % ezpp_cs(ez))
print("%g ar" % ezpp_ar(ez))
print("%g od" % ezpp_od(ez))
print("%g hp" % ezpp_hp(ez))
ezpp_free(ez)
```
Even though new base values are set, the values returned are still the original map values
Example from the insane diff of https://osu.ppy.sh/beatmapsets/37
```
5 cs
10 ar
10 od
10 hp
```

**Comment by Jeglet** [comment]
Well, disregard the AR, OD and HP part. Being dumb I forgot to set autocalc to 1. However the cs values still do not update, which was what made me curious about this in the first place.

**Comment by Jeglerjeg** [comment]
Solved by avoiding setting CS value after the map has been loaded, and avoiding setting nmiss after CS value has been set. Both of these scenarios reset CS to the default map value, which seems unintended to me however.
