### ISSUE TITLE
oppai 4.0.0 Python wheels only available for Windows

### ISSUE THREAD

**Issue by christopher-dG** [Francesco149/oppai-ng#73]
Something seems to have gone wrong with the deploy of 4.0.0 to PyPI.

https://pypi.org/project/oppai/3.3.0/#files
https://pypi.org/project/oppai/4.0.0/#files

**Comment by Francesco149** [comment]
ah yeah i need to manually build and upload the linux wheels but I dont wanna reinstall docker on this machine, ill try to remember to fix it

**Comment by Francesco149** [comment]
sorry for taking so long, I finally set up the build system for the manylinux wheels again and it should be fixed now
