### ISSUE TITLE
Incorrect AR<8 bonus in most (if not all) oppai ports

### ISSUE THREAD

**Issue by Rian8337** [Francesco149/oppai-ng#74]
https://github.com/Francesco149/oppai-ng/blob/bbbeb9f3c536b95b5c3e7fccbb94f6c69a099c80/oppai.c#L2104-L2107

should be

```c
  /* low ar bonus */
  else if (ez->ar < 8.0f) {
    ar_bonus += 0.01f * (8.0f - ez->ar);
  }
```

**Comment by Francesco149** [comment]
the 0.01 comes from a january commit. I don't think that change is live on leaderboards https://github.com/ppy/osu-performance/commit/60bc836c5ed0852c1807cb00c98f61c809838b17

**Comment by Rian8337** [comment]
Didn't they claim the AR<8 buff overlooked as of https://github.com/ppy/osu/pull/11476, though?

**Comment by Francesco149** [comment]
gotta check if live scores are already affected by this. if not i will merge it when they do
