### ISSUE TITLE
Certain map crashes oppai.exe

### ISSUE THREAD

**Issue by flesnuk** [Francesco149/oppai-ng#9]
(New-Object System.Net.WebClient).DownloadString("https://osu.ppy.sh/osu/1263398") | ./oppai.exe -

https://osu.ppy.sh/s/584389 -> https://osu.ppy.sh/b/1263398&m=0 (it is a loved map btw)

Tried another recent ranked map, and by chance, it crashed in Windows x64 too. 
https://osu.ppy.sh/b/1314214&m=0

I don't know if this happens on linux too. I will look into it. 
Any way to debug this and give useful info?

**Comment by Francesco149** [comment]
I think this is related to #7 which I already fixed locally cause it's not crashing for me, wait a bit more and I will release a newer ver so you can retest

**Comment by Francesco149** [comment]
uh interesting it's still crashing but only on windows, guess I'll debug

**Comment by Francesco149** [comment]
very interesting. I use ```strtod("inf", 0)``` to get a portable infinity value but on windows it returns 0.0. that's most likely the cause of the crash which makes it loop into out of bounds timing points

let's see if I can find a method that works on windows

**Comment by flesnuk** [comment]
This may be useful?

https://lists.nongnu.org/archive/html/lmi/2012-05/msg00021.html

**Comment by Francesco149** [comment]
I'm gonna upload new binaries soon, so you can test. reopen if it still crashes

**Comment by Francesco149** [comment]
I ended up just using the raw bitmask for inf and interpreting it as double

**Comment by Francesco149** [comment]
https://github.com/Francesco149/oppai-ng/releases/tag/1.1.18
